name: 📚 Documentation
description: Report an issue related to the documentation.
labels: "docs"
title: "[Docs] "

body:
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: This issue is related to the
      options:
        - master branch  https://mmocr.readthedocs.io/en/latest/
        - 1.x branch https://mmocr.readthedocs.io/en/dev-1.x/
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📚 The doc issue
      description: >
        A clear and concise description the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggest a potential alternative/fix
      description: >
        Tell us how we could improve the documentation in this regard.

  - type: markdown
    attributes:
      value: |
        ## Acknowledgement
        Thanks for taking the time to fill out this report.

        If you have already identified the reason, we strongly appreciate you creating a new PR to fix it [here](https://github.com/open-mmlab/mmocr/pulls)!
        Please refer to [here](https://mmocr.readthedocs.io/en/dev-1.x/notes/contribution_guide.html) for the contributing guidelines.

        You can also join our Wechat group or our slack to discuss together.
